import { defineConfig } from "@pandacss/dev";
import { ossPreset } from "./src/deployment/default/panda-preset";

// Optionally pull in the private brand preset, mirroring the `theme-package`
// alias swap in vite.config.ts. When the private package is installed it
// overrides brand tokens (colours, fonts) and brand recipe variants; otherwise
// the OSS default preset stands alone. The two are merged by Panda at codegen
// time — the build-time equivalent of Chakra's runtime theme swap.
//
// Panda loads this config as CommonJS, so `require` is the real (sync) require;
// Node 24 resolves the ESM private package through it.
let brandPreset: unknown;
try {
  brandPreset = (
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require("@microbit-foundation/ml-trainer-microbit/panda-preset") as {
      default: unknown;
    }
  ).default;
} catch {
  brandPreset = undefined;
}

export default defineConfig({
  preflight: true,
  // Vite uses the lightningcss transformer, which disables PostCSS, so Panda
  // runs via its CLI (codegen + cssgen) rather than the PostCSS plugin.
  // src/styled-system.css is generated by `npm run panda` and imported once in
  // main.tsx.
  jsxFramework: "react",
  // Drop Panda's default theme preset; the OSS preset supplies the full token
  // system (ported from Chakra). preset-base still provides the utilities.
  eject: true,
  presets: [
    "@pandacss/preset-base",
    ossPreset,
    ...(brandPreset ? [brandPreset] : []),
  ],
  include: ["./src/**/*.{ts,tsx}"],
  outdir: "styled-system",
  // shared-ui components forward `variant`/`size`/etc. as runtime props to the
  // recipe functions, so Panda's static analysis can't see which variants are
  // used and would emit no CSS for them. Generate every recipe variant.
  staticCss: {
    recipes: {
      button: ["*"],
      heading: ["*"],
      // Dialog size is chosen with responsive objects ({ base, md }) passed as a
      // runtime prop, so generate the breakpoint-prefixed variants too.
      card: ["*"],
      dialog: [{ size: ["*"], responsive: true }, { centered: ["*"] }],
      drawer: ["*"],
    },
  },
});
