name: 'pr-url'
on:
  pull_request:
    types: [opened]
jobs:
  pr-url:
    runs-on: ubuntu-latest
    steps:
      - uses: microbit-foundation/action-pr-url-template@v0.1.2
        with:
          uri-template: 'https://review-ml.microbit.org/{branch}/thenextgen/'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
